baseline_packages:
  - curl
  - wget
  - jq
  - git
  - vim
  - nano
  - htop
  - tmux
  - unzip
  - zip
  - rsync
  - ca-certificates
  - net-tools
  - dnsutils
  - lsof
  - iotop
  - nmap
  - openssh-client
  - python3
  - python3-pip
  - chrony
  - tree
  - kubectl
  - golang


baseline_timezone: "America/New_York"