on:
  push:
    branches:
      - Master
  workflow_dispatch:
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest 

    steps:
      - name: install ssh keys
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p "$HOME/.ssh"
          chmod 700 "$HOME/.ssh"
      
          # write private key
          printf '%s\n' "${{ secrets.SSH_PRIVATE_KEY }}" > "$KEYFILE"
          chmod 600 "$HOME/.ssh/id_rsa"
      
          # add host key
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> "$HOME/.ssh/known_hosts"
          chmod 600 "$HOME/.ssh/known_hosts"
      - name: connect and pull
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull && exit"
      - name: cleanup
        run: rm -rf ~/.ssh
